#!/bin/sh
# postinst script
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /etc/snmp/snmpd.conf  ]; then
  echo "snmpd exist already"
  exit 0
else

echo "snmpd conf not found"
        echo "Adding initial snmpd.conf"
        echo "rocommunity public localhost" > /etc/snmp/snmpd.conf
        echo "Adding snmpd.service to systemd"
echo "
#
# SNMP agent service file for systemd
#
#
# The service should be enabled, i.e. snmpd should start during machine boot.
# Socket activation shall not be used. See README.systemd for details.

[Unit]
Description=Simple Network Management Protocol (SNMP) daemon.
After=syslog.target network.target

[Service]
# Type=notify is also supported. It should be set when snmpd.socket is not used.
Type=simple
ExecStart=/usr/local/sbin/snmpd -A -c /etc/snmp/snmpd.conf

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/snmpd.service

echo "Activate manually"

fi

db_stop

exit 0
